export const GET_MOVIES_START = "GET_MOVIES_START";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR";
export const GET_SINGLE_MOVIE_START = "GET_SINGLE_MOVIE_START";
export const GET_SINGLE_MOVIE_SUCCESS = "GET_SINGLE_MOVIE_SUCCESS";
export const GET_SINGLE_MOVIE_ERROR = "GET_SINGLE_MOVIE_ERROR";
export const SET_ACTIVE_TOPBAR = "SET_ACTIVE_TOPBAR";
export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";
